"""中文 → 英文搜索词词典（轻量级，无额外依赖）
用于将中文查询翻译为英文，使 CLIP 检索准确匹配英语 caption。
"""

import re

# 常用搜索词映射（按长度降序排列，优先匹配最长词组）
_TRANSLATION_MAP: list[tuple[str, str]] = [
    # ── 动物 ──
    ("长颈鹿", "giraffe"),
    ("大熊猫", "panda"),
    ("考拉", "koala"),
    ("松鼠", "squirrel"),
    ("猴子", "monkey"),
    ("大象", "elephant"),
    ("老虎", "tiger"),
    ("狮子", "lion"),
    ("熊猫", "panda"),
    ("企鹅", "penguin"),
    ("海豚", "dolphin"),
    ("蝴蝶", "butterfly"),
    ("蜘蛛", "spider"),
    ("兔子", "rabbit"),
    ("老鼠", "mouse"),
    ("鹦鹉", "parrot"),
    ("猫头鹰", "owl"),
    ("海鸥", "seagull"),
    ("孔雀", "peacock"),
    ("骆驼", "camel"),
    ("乌龟", "turtle"),
    ("蛇", "snake"),
    ("鱼", "fish"),
    ("猫", "cat"),
    ("狗", "dog"),
    ("鸟", "bird"),
    ("马", "horse"),
    ("牛", "cow"),
    ("羊", "sheep"),
    ("猪", "pig"),
    ("鸡", "chicken"),
    ("鸭", "duck"),
    ("熊", "bear"),
    ("鹿", "deer"),
    ("狼", "wolf"),
    ("狐", "fox"),
    ("猴", "monkey"),
    # ── 人物 ──
    ("女人", "woman"),
    ("男人", "man"),
    ("男孩", "boy"),
    ("女孩", "girl"),
    ("黑人", "black person"),
    ("白人", "white person"),
    ("亚洲人", "asian person"),
    ("中国人", "chinese person"),
    ("儿童", "children"),
    ("小孩", "child"),
    ("婴儿", "baby"),
    ("人们", "people"),
    ("人群", "crowd"),
    ("家庭", "family"),
    ("朋友", "friend"),
    ("警察", "policeman"),
    ("医生", "doctor"),
    ("工人", "worker"),
    ("厨师", "chef"),
    ("运动员", "athlete"),
    ("骑手", "rider"),
    ("人", "person"),
    ("脸", "face"),
    ("手", "hand"),
    ("眼睛", "eye"),
    # ── 自然风景 ──
    ("森林", "forest"),
    ("海滩", "beach"),
    ("山脉", "mountain"),
    ("沙漠", "desert"),
    ("瀑布", "waterfall"),
    ("河流", "river"),
    ("湖泊", "lake"),
    ("海洋", "ocean"),
    ("草原", "grassland"),
    ("田野", "field"),
    ("花园", "garden"),
    ("公园", "park"),
    ("夜空", "night sky"),
    ("星空", "starry sky"),
    ("日落", "sunset"),
    ("日出", "sunrise"),
    ("彩虹", "rainbow"),
    ("雪地", "snowy"),
    ("雪景", "snow"),
    ("山", "mountain"),
    ("花", "flower"),
    ("树", "tree"),
    ("草", "grass"),
    ("云", "cloud"),
    ("雨", "rain"),
    ("雪", "snow"),
    # ── 建筑与城市 ──
    ("摩天大楼", "skyscraper"),
    ("教堂", "church"),
    ("寺庙", "temple"),
    ("桥梁", "bridge"),
    ("城堡", "castle"),
    ("钟楼", "clock tower"),
    ("灯塔", "lighthouse"),
    ("风车", "windmill"),
    ("建筑", "building"),
    ("房子", "house"),
    ("街道", "street"),
    ("城市", "city"),
    ("村庄", "village"),
    ("车站", "station"),
    ("机场", "airport"),
    ("码头", "dock"),
    ("城墙", "wall"),
    ("塔", "tower"),
    ("门", "door"),
    ("窗", "window"),
    # ── 交通 ──
    ("自行车", "bicycle"),
    ("摩托车", "motorcycle"),
    ("公交车", "bus"),
    ("出租车", "taxi"),
    ("卡车", "truck"),
    ("火车", "train"),
    ("飞机", "airplane"),
    ("直升机", "helicopter"),
    ("轮船", "ship"),
    ("帆船", "sailboat"),
    ("皮划艇", "kayak"),
    ("汽车", "car"),
    ("车辆", "vehicle"),
    ("车", "car"),
    ("船", "boat"),
    ("路", "road"),
    ("灯", "light"),
    # ── 物品 ──
    ("笔记本电脑", "laptop"),
    ("手机", "phone"),
    ("电脑", "computer"),
    ("键盘", "keyboard"),
    ("相机", "camera"),
    ("眼镜", "glasses"),
    ("手表", "watch"),
    ("雨伞", "umbrella"),
    ("书包", "backpack"),
    ("吉他", "guitar"),
    ("钢琴", "piano"),
    ("小提琴", "violin"),
    ("自行车", "bicycle"),
    ("椅子", "chair"),
    ("桌子", "table"),
    ("床", "bed"),
    ("灯", "lamp"),
    ("钟", "clock"),
    ("书", "book"),
    ("笔", "pen"),
    ("钥匙", "key"),
    ("杯子", "cup"),
    ("碗", "bowl"),
    ("刀", "knife"),
    ("叉子", "fork"),
    ("勺子", "spoon"),
    ("瓶子", "bottle"),
    ("花盆", "flower pot"),
    ("花瓶", "vase"),
    ("玩具", "toy"),
    ("球", "ball"),
    ("旗帜", "flag"),
    ("雕像", "statue"),
    ("雕塑", "sculpture"),
    # ── 食物 ──
    ("比萨", "pizza"),
    ("汉堡", "hamburger"),
    ("三明治", "sandwich"),
    ("意大利面", "pasta"),
    ("寿司", "sushi"),
    ("蛋糕", "cake"),
    ("冰淇淋", "ice cream"),
    ("巧克力", "chocolate"),
    ("水果", "fruit"),
    ("蔬菜", "vegetable"),
    ("面包", "bread"),
    ("米饭", "rice"),
    ("鸡蛋", "egg"),
    ("牛奶", "milk"),
    ("咖啡", "coffee"),
    ("茶", "tea"),
    ("果汁", "juice"),
    ("酒", "wine"),
    ("肉", "meat"),
    ("鱼", "fish"),
    ("苹果", "apple"),
    ("香蕉", "banana"),
    ("橙子", "orange"),
    ("西瓜", "watermelon"),
    ("葡萄", "grape"),
    ("草莓", "strawberry"),
    # ── 颜色 ──
    ("红色", "red"),
    ("蓝色", "blue"),
    ("绿色", "green"),
    ("黄色", "yellow"),
    ("白色", "white"),
    ("黑色", "black"),
    ("紫色", "purple"),
    ("橙色", "orange"),
    ("粉色", "pink"),
    ("灰色", "gray"),
    ("棕色", "brown"),
    ("金色", "golden"),
    ("彩色", "colorful"),
    ("鲜艳", "bright"),
    ("暗", "dark"),
    # ── 场景 ──
    ("室内", "indoor"),
    ("户外", "outdoor"),
    ("夜景", "night"),
    ("白天", "daytime"),
    ("早晨", "morning"),
    ("傍晚", "evening"),
    ("婚礼", "wedding"),
    ("派对", "party"),
    ("音乐会", "concert"),
    ("运动会", "sports"),
    ("比赛", "game"),
    ("市场", "market"),
    ("商场", "mall"),
    ("办公室", "office"),
    ("教室", "classroom"),
    ("厨房", "kitchen"),
    ("卧室", "bedroom"),
    ("客厅", "living room"),
    ("浴室", "bathroom"),
    ("餐厅", "restaurant"),
    ("博物馆", "museum"),
    ("图书馆", "library"),
    ("体育馆", "stadium"),
    ("游泳池", "pool"),
    ("操场", "playground"),
    ("停车场", "parking lot"),
    ("工地", "construction"),
    # ── 动作 ──
    ("跑步", "running"),
    ("行走", "walking"),
    ("坐着", "sitting"),
    ("站立", "standing"),
    ("跳跃", "jumping"),
    ("跳舞", "dancing"),
    ("唱歌", "singing"),
    ("演奏", "playing music"),
    ("画画", "painting"),
    ("写作", "writing"),
    ("阅读", "reading"),
    ("做饭", "cooking"),
    ("吃饭", "eating"),
    ("喝水", "drinking"),
    ("游泳", "swimming"),
    ("骑行", "cycling"),
    ("开车", "driving"),
    ("飞行", "flying"),
    ("睡觉", "sleeping"),
    ("工作", "working"),
    ("学习", "studying"),
    ("拍照", "taking a photo"),
    ("微笑", "smiling"),
    ("哭泣", "crying"),
    ("大笑", "laughing"),
    # ── 其他 ──
    ("古风", "ancient"),
    ("现代", "modern"),
    ("老旧", "old"),
    ("新", "new"),
    ("大", "big"),
    ("小", "small"),
    ("高", "tall"),
    ("矮", "short"),
    ("长", "long"),
    ("短", "short"),
    ("美丽", "beautiful"),
    ("漂亮", "pretty"),
    ("丑陋", "ugly"),
    ("快乐", "happy"),
    ("悲伤", "sad"),
    ("安静", "quiet"),
    ("热闹", "busy"),
    ("脏", "dirty"),
    ("干净", "clean"),
    ("空", "empty"),
    ("满", "full"),
    ("开放", "open"),
    ("关闭", "closed"),
    ("可爱", "cute"),
    ("搞笑", "funny"),
    ("奇怪", "strange"),
    ("恐怖", "scary"),
    ("危险", "dangerous"),
    ("安全", "safe"),
]

# 按长度降序排序以保证最长匹配优先
_TRANSLATION_MAP.sort(key=lambda x: -len(x[0]))


def has_chinese(text: str) -> bool:
    """检测文本是否包含中文字符"""
    return bool(re.search(r"[一-鿿㐀-䶿]", text))


def chinese_to_english(text: str) -> str:
    """将中文查询中的已知词条翻译为英文，返回追加英文关键词后的查询

    示例:
        "猴子" → "monkey"
        "红色汽车" → "red car"
        "森林里的猴子" → "forest monkey"
    """
    if not has_chinese(text):
        return text

    result = text
    translated_terms = []

    for zh, en in _TRANSLATION_MAP:
        if zh in result:
            translated_terms.append(en)
            # 移除已匹配的中文，避免重复匹配子串
            result = result.replace(zh, "", 1)

    if translated_terms:
        # 用翻译后的英文替换原文查询（完全替换，不走 CLIP 中文编码）
        english_query = " ".join(translated_terms)
        return english_query

    # 没有找到任何翻译词条 → 返回原文，CLIP 尽力而为
    return text
